config/routes.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

Diaspora::Application.routes.draw do
  resources :status_messages, :only => [:create, :destroy, :show]
  resources :comments,        :only => [:create]
  resources :requests,        :only => [:destroy, :create]
  resources :services
  resources :posts,           :only => [:show], :path => '/p/'



  match '/people/share_with' => 'people#share_with', :as => 'share_with'
  resources :people do
    resources :status_messages
    resources :photos
  end

  match '/people/by_handle' => 'people#retrieve_remote', :as => 'person_by_handle'
  match '/auth/:provider/callback' => 'services#create'
  match '/auth/failure' => 'services#failure'

  match 'photos/make_profile_photo' => 'photos#make_profile_photo'
  resources :photos, :except => [:index]

  devise_for :users, :controllers => {:registrations => "registrations",
                                      :password      => "devise/passwords",
                                      :invitations   => "invitations"}
  # added public route to user
  match 'public/:username',          :to => 'users#public'
  match 'getting_started',           :to => 'users#getting_started', :as => 'getting_started'
  match 'getting_started_completed', :to => 'users#getting_started_completed'
  match 'users/export',              :to => 'users#export'
  match 'users/export_photos',       :to => 'users#export_photos'
  match 'login',                     :to => 'users#sign_up'
  resources :users,                  :except => [:create, :new, :show]

  match 'aspects/move_contact',      :to => 'aspects#move_contact', :as => 'move_contact'
  match 'aspects/add_to_aspect',     :to => 'aspects#add_to_aspect', :as => 'add_to_aspect'
  match 'aspects/remove_from_aspect',:to => 'aspects#remove_from_aspect', :as => 'remove_from_aspect'
  match 'aspects/manage',            :to => 'aspects#manage'
  resources :aspects,                :except => [:edit]

  #public routes
  match 'webfinger',            :to => 'publics#webfinger'
  match 'hcard/users/:id',      :to => 'publics#hcard'
  match '.well-known/host-meta',:to => 'publics#host_meta'
  match 'receive/users/:id',    :to => 'publics#receive'
  match 'hub',                  :to => 'publics#hub'

  #root
  root :to => 'home#show'
end

app/models/person.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

require File.join(Rails.root, 'lib/hcard')

class Person
  include MongoMapper::Document
  include ROXML
  include Encryptor::Public
  require File.join(Rails.root, 'lib/diaspora/web_socket')
  include Diaspora::Socketable

  xml_accessor :_id
  xml_accessor :diaspora_handle
  xml_accessor :url
  xml_accessor :profile, :as => Profile
  xml_reader :exported_key

  key :url, String
  key :diaspora_handle, String, :unique => true
  key :serialized_public_key, String

  key :owner_id, ObjectId

  one :profile, :class_name => 'Profile'
  validates_associated :profile
  delegate :last_name, :to => :profile
  before_save :downcase_diaspora_handle

  def downcase_diaspora_handle
    diaspora_handle.downcase!
  end

  belongs_to :owner, :class_name => 'User'

  timestamps!

  before_destroy :remove_all_traces
  before_validation :clean_url
  validates_presence_of :url, :profile, :serialized_public_key
  validates_uniqueness_of :diaspora_handle, :case_sensitive => false
  #validates_format_of :url, :with =>
  #  /^(https?):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*(\.[a-z]{2,5})?(:[0-9]{1,5})?(\/.*)?$/ix

  ensure_index :diaspora_handle

  scope :searchable, where('profile.searchable' => true)

  attr_accessible :profile

  def self.search(query)
    return [] if query.to_s.empty?
    query_tokens = query.to_s.strip.split(" ")
    full_query_text = Regexp.escape(query.to_s.strip)

    p = []

    query_tokens.each do |token|
      q = Regexp.escape(token.to_s.strip)
      p = Person.searchable.all('profile.first_name' => /^#{q}/i, 'limit' => 30) \
 | Person.searchable.all('profile.last_name' => /^#{q}/i, 'limit' => 30) \
 | Person.searchable.all('diaspora_handle' => /^#{q}/i, 'limit' => 30) \
 | p
    end

    return p
  end

  def name
    @name ||= if profile.first_name.nil? || profile.first_name.blank?
                self.diaspora_handle
              else
                "#{profile.first_name.to_s} #{profile.last_name.to_s}"
              end
  end
  def first_name
    @first_name ||= if profile.first_name.nil? || profile.first_name.blank?
                self.diaspora_handle.split('@').first
              else
                profile.first_name.to_s
              end
  end
  def owns?(post)
    self.id == post.person.id
  end

  def receive_url
    "#{self.url}receive/users/#{self.id}/"
  end

  def public_url
    "#{self.url}public/#{self.owner.username}"
  end


  def public_key_hash
    Base64.encode64 OpenSSL::Digest::SHA256.new(self.exported_key).to_s
  end

  def public_key
    OpenSSL::PKey::RSA.new(serialized_public_key)
  end

  def exported_key
    serialized_public_key
  end

  def exported_key= new_key
    raise "Don't change a key" if serialized_public_key
    @serialized_public_key = new_key
  end

  #database calls
  def self.by_account_identifier(identifier)
    identifier = identifier.strip.downcase.gsub('acct:', '')
    self.first(:diaspora_handle => identifier)
  end

  def self.local_by_account_identifier(identifier)
    person = self.by_account_identifier(identifier)
   (person.nil? || person.remote?) ? nil : person
  end

  def self.build_from_webfinger(profile, hcard)
    return nil if profile.nil? || !profile.valid_diaspora_profile?
    new_person = Person.new
    new_person.exported_key = profile.public_key
    new_person.id = profile.guid
    new_person.diaspora_handle = profile.account
    new_person.url = profile.seed_location

    #hcard_profile = HCard.find profile.hcard.first[:href]
    Rails.logger.info("event=webfinger_marshal valid=#{new_person.valid?} target=#{new_person.diaspora_handle}")
    new_person.url = hcard[:url]
    new_person.profile = Profile.new( :first_name => hcard[:given_name],
                                      :last_name  => hcard[:family_name],
                                      :image_url  => hcard[:photo],
                                      :image_url_medium  => hcard[:photo_medium],
                                      :image_url_small  => hcard[:photo_small],
                                      :searchable => hcard[:searchable])

    new_person.save! ? new_person : nil
  end

  def remote?
    owner_id.nil?
  end

  def as_json(opts={})
    {
      :person => {
        :id           => self.id,
        :name         => self.name,
        :url          => self.url,
        :exported_key => exported_key,
        :diaspora_handle => self.diaspora_handle
      }
    }
  end

  def self.from_post_comment_hash(hash)
    person_ids = hash.values.flatten.map!{|c| c.person_id}.uniq
    people = where(:id.in => person_ids).fields(:profile)
    people_hash = {}
    people.each{|p| people_hash[p.id] = p}
    people_hash
  end

  protected

  def clean_url
    self.url ||= "http://localhost:3000/" if self.class == User
    if self.url
      self.url = 'http://' + self.url unless self.url.match(/https?:\/\//)
      self.url = self.url + '/' if self.url[-1, 1] != '/'
    end
  end

  private
  def remove_all_traces
    Post.all(:person_id => id).each { |p| p.delete }
  end
end

app/controllers/people_controller.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

class PeopleController < ApplicationController
  before_filter :authenticate_user!

  respond_to :html
  respond_to :json, :only => [:index, :show]

  def index
    @aspect = :search

    @people = Person.search(params[:q]).paginate :page => params[:page], :per_page => 25, :order => 'created_at DESC'
    if @people.count == 1
      redirect_to @people.first
    else
      @hashes = hashes_for_people(@people, @aspects)
      #only do it if it is an email address
      if params[:q].try(:match, Devise.email_regexp)
        webfinger(params[:q])
      end
    end
  end

  def hashes_for_people people, aspects
    ids = people.map{|p| p.id}
    requests = {}
    Request.all(:from_id.in => ids, :to_id => current_user.person.id).each do |r|
      requests[r.to_id] = r
    end
    contacts = {}
    Contact.all(:user_id => current_user.id, :person_id.in => ids).each do |contact|
      contacts[contact.person_id] = contact
    end
    people.map{|p|
      {:person => p,
        :contact => contacts[p.id],
        :request => requests[p.id],
        :aspects => aspects}
    }
  end

  def show
    @person = Person.find(params[:id].to_id)
    @post_type = :all

    if @person
      @incoming_request = Request.to(current_user).from(@person).first
      @outgoing_request = Request.from(current_user).to(@person).first

      @profile = @person.profile
      @contact = current_user.contact_for(@person)
      @aspects_with_person = []

      if @contact
        @aspects_with_person = @contact.aspects
      end

      if (@person != current_user.person) && (!@contact || @contact.pending)
        @commenting_disabled = true
      else
        @commenting_disabled = false
      end

      @posts = current_user.posts_from(@person).paginate :page => params[:page]
      @post_hashes = hashes_for_posts @posts

      respond_with @person, :locals => {:post_type => :all}

    else
      flash[:error] = I18n.t 'people.show.does_not_exist'
      redirect_to people_path
    end
  end

  def destroy
    current_user.disconnect(current_user.visible_person_by_id(params[:id]))
    respond_with :location => root_url
  end

  def edit
    @aspect  = :person_edit
    @person  = current_user.person
    @profile = @person.profile
  end

  def update
    # upload and set new profile photo
    params[:profile] ||= {}
    params[:profile][:searchable] ||= false
    params[:profile][:photo] = Photo.first(:person_id => current_user.person.id, :id => params[:photo_id]) if params[:photo_id]

    if current_user.update_profile params[:profile]
      flash[:notice] = I18n.t 'people.update.updated'
    else
      flash[:error] = I18n.t 'people.update.failed'
    end

    if params[:getting_started]
      redirect_to getting_started_path(:step => params[:getting_started].to_i+1)
    else
      redirect_to edit_person_path
    end
  end

  def retrieve_remote
    if params[:diaspora_handle]
      webfinger(params[:diaspora_handle], :single_aspect_form => true)
      render :nothing => true
    else
      render :nothing => true, :status => 422
    end
  end

  def share_with
    @person = Person.find(params[:id].to_id)
    @contact = current_user.contact_for(@person)
    @aspects_with_person = []

    if @contact
      @aspects_with_person = @contact.aspects
    end

    @aspects_without_person = @aspects.reject do |aspect|
      @aspects_with_person.include?(aspect)
    end

    render :layout => nil
  end

  private
  def hashes_for_posts posts
    post_ids = posts.map{|p| p.id}
    comment_hash = Comment.hash_from_post_ids post_ids
    person_hash = Person.from_post_comment_hash comment_hash
    photo_hash = Photo.hash_from_post_ids post_ids

    posts.map do |post|
      {:post => post,
        :person => @person,
        :photos => photo_hash[post.id],
        :comments => comment_hash[post.id].map do |comment|
          {:comment => comment,
            :person => person_hash[comment.person_id],
          }
        end,
      }
    end
  end

  def webfinger(account, opts = {})
    Resque.enqueue(Jobs::SocketWebfinger, current_user.id, account, opts)
  end
end

app/helpers/people_helper.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

module PeopleHelper

  def request_partial single_aspect_form
    if single_aspect_form
      'requests/new_request_with_aspect_to_person'
    else
      'requests/new_request_to_person'
    end
  end

  def search_or_index
    if params[:q]
      I18n.t 'people.helper.results_for',:params => params[:q]
    else
      I18n.t "people.helper.people_on_pod_are_aware_of"
    end
  end
end

app/views/people/_aspect_list.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- content_for :head do
  =javascript_include_tag 'contact-list'

  :javascript
    $(document).ready(function() {
      $("#edit_contact_aspects").click(function(evt){
        evt.preventDefault();
        $(".badges").fadeOut(200, function(){
          $(".edit").fadeIn(200);
        });
      });

      $("#done_contact_aspects").click(function(evt){
        evt.preventDefault();
        $(".edit").fadeOut(200, function(){
          $(".badges").fadeIn(200);
        });
      });
    });

.aspects
  - if !contact
    %h4
      = t('people.show.not_connected', :name => person.first_name)
  - elsif contact.pending
    %h4
      = t('people.person.pending_request')

  .badges{:class => ("hidden" if !contact)}
    - for aspect in aspects_with_person
      = render :partial => 'aspects/aspect_badge', :locals => {:aspect => aspect}
    .right
      = link_to "edit aspect membership", "#", :id=> "edit_contact_aspects"

  .edit{:class => ("hidden" if contact)}

    = render :partial => 'people/share_with_pane',
        :locals => {:person => person,
          :contact => contact,
          :aspects_with_person => aspects_with_person,
          :aspects_without_person => aspects_without_person}

    - if contact
      .right
        = link_to "done editing", "#", :id => "done_contact_aspects"
      = link_to t('people.profile_sidebar.remove_contact'), person, :confirm => t('are_you_sure'), :method => :delete

app/views/people/_edit.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- content_for :page_title do
  = t('.edit_profile')

= form_tag person_path(@person), :method => :put, :multipart => true, :id => 'update_profile_form' do
  %h3
    = t('people.edit.your_profile')
    .description
      = t('people.edit.info_available_to')

  = error_messages_for @person

  %h4
    = t('people.edit.your_name')
    = text_field_tag 'profile[first_name]', @profile.first_name, :placeholder => t('people.edit.first_name')
    = text_field_tag 'profile[last_name]', @profile.last_name, :placeholder => t('people.edit.last_name')

  %h4
    = t('people.edit.your_gender')
    %br
    = text_field_tag 'profile[gender]', @profile.gender, :placeholder => t("fill_me_out")

  %h4
    = t('people.edit.your_birthday')
    %br
    = select_date @person.profile.birthday, :prompt => true,
      :default => true, :order => t('date.order'), :start_year => 2000, :end_year => 1930, :prefix => 'profile[date]'

  %h4
    = t('people.edit.your_bio')
    = text_area_tag 'profile[bio]', @profile.bio, :rows => 5, :placeholder => t('fill_me_out')

  %h4
    = t('people.edit.your_photo')
    = render 'photos/new_profile_photo'
    %br

  %h4
    = t('search')
    %p{:class=>"checkbox_select"}
      = label_tag 'profile[searchable]', t('people.edit.allow_search')
      = check_box_tag 'profile[searchable]', true, @person.profile.searchable

  = hidden_field_tag :getting_started, @step if @step

  .submit_block
    =yield(:submit_block)

app/views/people/_person.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

%li.message{:id => person.id}

  .right{:style=>"display:inline;"}
    - if person.owner_id == current_user.id
      = t('.thats_you')
    - elsif contact && !contact.pending
      = t('.already_connected')
    - elsif (contact && contact.pending) || request
      = t('.pending_request')
    - else
      - single_aspect_form ||= nil
      = link_to "start sharing",
        {:controller => "people",
        :action => "share_with",
        :id => person.id},
        :class => 'button share_with_button'

  = person_image_link(person)

  .content
    %span.from
      =person_link(person)


    .info
      = person.diaspora_handle

app/views/people/_profile_photo_upload.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


#profile_photo_upload
  = owner_image_tag(:thumb_medium)
  = file_field_tag 'profile[image]'

  -if !@aspect.nil? && @aspect != :getting_started 
    %p
      \...#{t('photos.new_profile_photo.or_select_one')}
      = link_to t('_photos'), person_photos_path(@person)

app/views/people/_profile_sidebar.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- content_for :head do
  :javascript
    $(document).ready(function(){
      $('.delete').bind('ajax:success', function() {
        $(this).closest('li').fadeOut(200);
      });
      $('.delete').bind('ajax:failure', function() {
        alert("#{t('.cannot_remove', :name => person.name)}");
      });
    });


#profile
  .profile_photo
    = person_image_link(person, :size => :thumb_large, :to => :photos)

  - if person == current_user.person
    %p
      = link_to t('people.profile_sidebar.edit_my_profile'), edit_person_path(person)

    %hr{:style=>"width:300px;"}

  %ul
    - unless person == current_user.person
      %li
        = render :partial => 'people/aspect_list',
          :locals => {:person => person,
                      :contact => contact,
                      :aspects_with_person => @aspects_with_person,
                      :aspects_without_person => @aspects.reject{ |aspect| @aspects_with_person.include?(aspect)}}
      %br
      %hr{:style=>"width:300px;"}

  -if (contact && !contact.pending?) || person == current_user.person
    %ul#profile_information
      %li
        %h3 #{t('.bio')}
        = markdownify(person.profile.bio, :newlines => true)

      %li
        .span-4
          %h3 #{t('.gender')}
          = person.profile.gender

        .span-4.last
          %h3 #{t('.born')}
          = t('ago', :time => time_ago_in_words(person.profile.birthday)) if @person.profile.birthday

app/views/people/_share_with_pane.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.contact_list#aspects_list
  %ul
    - for aspect in aspects_with_person
      %li{:data=>{:guid=>aspect.id}}
        %span.name
          = link_to aspect.name, aspect
        .right
          = aspect_membership_button(aspect.id, contact, person)

    - for aspect in aspects_without_person
      %li{:data=>{:guid=>aspect.id}}
        %span.name
          = link_to aspect.name, aspect
        .right
          = aspect_membership_button(aspect.id, contact, person)

app/views/people/edit.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


#section_header
  %h2
    = t('settings')
  %ul#settings_nav
    %li=link_to t('profile'), edit_person_path(current_user.person)
    %li=link_to t('account'), edit_user_path(current_user)
    %li=link_to t('_services'), services_path

.span-19.prepend-5.last
  - content_for :submit_block do
    = link_to t('cancel'), edit_user_path(current_user)
    = t('or')
    = submit_tag t('.update_profile')
  = render :partial => 'people/edit'

app/views/people/index.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- content_for :page_title do
  = t('search')

- content_for :head do
  = include_javascripts :people

.span-24.last
  - if params[:q].blank?
    %h2
      =t('.no_results')
  - else
    %h2#search_title
      =t('.results_for')
      %span.term
        = params[:q]


.span-15.append-1

  - if @hashes.empty?
    %p
      =t('.no_one_found')

  - else
    %ul{:class => 'stream people', :id => 'people_stream'}
      - for hash in @hashes
        = render :partial => 'people/person', :locals => hash

    = will_paginate @people

.span-8.last
  %h4
    = t('.couldnt_find_them_send_invite')
  = render "shared/invitations", :invites => @invites

app/views/people/share_with.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

#share_with
  .share_with_header
    = person_image_link(@person, :size => :thumb_medium)
    %h3
      = "Start sharing with #{@person.name}"
    %p
      = "Once #{@person.first_name} accepts, you'll start seeing each other's posts on Diaspora"

  = render :partial => 'share_with_pane',
    :locals => {:person => @person,
                :contact => @contact,
                :aspects_with_person => @aspects_with_person,
                :aspects_without_person => @aspects_without_person}

app/views/people/show.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- content_for :page_title do
  = @person.name

.span-24.last
  #author_info
    .from{:style=>"padding-left:0;display:block;"}
      %h2{:style=>"display:block;"}
        = @person.name
        .right{:style => "top:0;"}
          %span.description
            = @person.diaspora_handle

      #person_nav_links
        = link_to t('layouts.header.view_profile'), person_path(@person)
        = link_to t('_photos'), person_photos_path(@person)

.span-8.append-1.last
  = render :partial => 'people/profile_sidebar', :locals => {:person => @person, :contact => @contact}

.span-15.last
  - unless @contact || current_user.person == @person
    - if @incoming_request
      .floating
        %h3
          = t('.incoming_request')
        %h4
          = link_to t('.return_to_aspects'), aspects_manage_path
          = t('.to_accept_or_ignore')

  - if @posts.count > 0
    -if @post_type == :photos
      %h4
        = t('_photos')
      = render 'photos/index', :photos => @posts
    - else
      %h4
        - if @contact
          = t('.recent_posts')
        - else
          = t('.recent_public_posts')

      = render 'shared/stream', :posts => @post_hashes
    = will_paginate @posts

  - else
    %ul#stream
      %li
        %h3= t('.no_posts')