config/routes.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

Diaspora::Application.routes.draw do
  resources :status_messages, :only => [:create, :destroy, :show]
  resources :comments,        :only => [:create]
  resources :requests,        :only => [:destroy, :create]
  resources :services
  resources :posts,           :only => [:show], :path => '/p/'



  match '/people/share_with' => 'people#share_with', :as => 'share_with'
  resources :people do
    resources :status_messages
    resources :photos
  end

  match '/people/by_handle' => 'people#retrieve_remote', :as => 'person_by_handle'
  match '/auth/:provider/callback' => 'services#create'
  match '/auth/failure' => 'services#failure'

  match 'photos/make_profile_photo' => 'photos#make_profile_photo'
  resources :photos, :except => [:index]

  devise_for :users, :controllers => {:registrations => "registrations",
                                      :password      => "devise/passwords",
                                      :invitations   => "invitations"}
  # added public route to user
  match 'public/:username',          :to => 'users#public'
  match 'getting_started',           :to => 'users#getting_started', :as => 'getting_started'
  match 'getting_started_completed', :to => 'users#getting_started_completed'
  match 'users/export',              :to => 'users#export'
  match 'users/export_photos',       :to => 'users#export_photos'
  match 'login',                     :to => 'users#sign_up'
  resources :users,                  :except => [:create, :new, :show]

  match 'aspects/move_contact',      :to => 'aspects#move_contact', :as => 'move_contact'
  match 'aspects/add_to_aspect',     :to => 'aspects#add_to_aspect', :as => 'add_to_aspect'
  match 'aspects/remove_from_aspect',:to => 'aspects#remove_from_aspect', :as => 'remove_from_aspect'
  match 'aspects/manage',            :to => 'aspects#manage'
  resources :aspects,                :except => [:edit]

  #public routes
  match 'webfinger',            :to => 'publics#webfinger'
  match 'hcard/users/:id',      :to => 'publics#hcard'
  match '.well-known/host-meta',:to => 'publics#host_meta'
  match 'receive/users/:id',    :to => 'publics#receive'
  match 'hub',                  :to => 'publics#hub'

  #root
  root :to => 'home#show'
end

app/views/shared/_add_contact.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


%h4
  = t('aspects.manage.add_a_new_contact')
  = info_text(t('.enter_a_diaspora_username'))

= form_tag(person_by_handle_path, :id => "new_request_to_#{aspect_id}", :class => "webfinger_form", :remote => true) do
  = search_field_tag :diaspora_handle,'', :id => "request_d_handle_to_#{aspect_id}", :results => 5, :placeholder => t('.diaspora_handle')
  = hidden_field_tag :aspect_id, aspect_id
  = submit_tag t('.create_request')

  %p{:style => "margin:12px 0 24px 0px;color:#999;text-align:center;"}
    = t('.your_diaspora_username_is', :diaspora_handle  => current_user.diaspora_handle)

#loader.hidden
  = image_tag 'ajax-loader.gif'

%ul#request_result{:aspect_id => aspect_id}
  %li.error.hidden
    #message
      = link_to t('.know_email'), new_user_invitation_path

app/views/shared/_add_remove_services.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


%ul.stream#service_stream
  - for service in @services
    %h3
      %b= service.provider
      = t('services.index.logged_in_as')
      %b= service.nickname
      = link_to t('services.index.disconnect'), service_path(service), :confirm => t('services.index.really_disconnect', :service => service.provider), :method => :delete

- unless @services.any?{|x| x.provider == 'twitter'}
  %h4= link_to t('services.index.connect_to_twitter'), "/auth/twitter" if SERVICES['twitter']['consumer_key']!= ""

- unless @services.any?{|x| x.provider == 'facebook'}
  %h4= link_to t('services.index.connect_to_facebook'), "/auth/facebook" if SERVICES['facebook']['app_id'] !=""

app/views/shared/_author_info.html.haml
#author_info
  = person_image_link(person)
  .from
    %h2
      = person.name

      - if post.public?
        %span.arrow ➔
        %span.aspect_badge.public
          =t('the_world')

      - elsif current_user.owns?(post)
        %span.arrow ➔
        =aspect_badge(aspects_with_post(post.aspects, post))

    #person_nav_links
      = link_to t('layouts.header.view_profile'), person_path(person)
      = link_to t('_photos'), person_photos_path(person)

app/views/shared/_contact_list.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


.contact_list
  = search_field_tag :contact_search, "", :class => 'contact_list_search', :results => 5, :placeholder => t('.all_contacts')
  %ul
    - for hash in contact_hashes
      %li
        %span.name
          = link_to hash[:person].name, hash[:person]
        .right
          = aspect_membership_button(aspect_id, hash[:contact], hash[:person])

app/views/shared/_invitations.haml
- if APP_CONFIG[:invites_off]
  = t('.invites_closed')
-else
  -if invites > 0
    = link_to t('.invite_someone'), new_user_invitation_path, :title => t('.invite_someone')
    = t('.invitations_left', :count => invites) 
  - else
    = t('.dont_have_now')

app/views/shared/_mail_signup_form.erb
<!-- Begin MailChimp Signup Form -->
<%= javascript_include_tag 'vendor/mailchimp/jquery126.min.js', 'vendor/mailchimp/jquery.validate.js', 'vendor/mailchimp/jquery.form.js' %>
<div id="mc_embed_signup">
<form action="http://joindiaspora.us1.list-manage.com/subscribe/post?u=d759919b94f9cdcf39d204f3f&amp;id=7b5ceb2f8b" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank">
	
<div class="mc-field-group">
<input type="text" value="" name="EMAIL" class="required email" placeholder="Email" id="mce-EMAIL">
</div>
		<div><input type="submit" value="<%= t('devise.shared.mail_signup_form.sign_up_for_an_invite') %>" name="subscribe" id="mc-embedded-subscribe" class="btn"></div>
		<div id="mce-responses">
			<div class="response" id="mce-error-response" style="display:none"></div>
			<div class="response" id="mce-success-response" style="display:none"></div>
		</div>
</form>
</div>

<script type="text/javascript">
var fnames = new Array();var ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[3]='MMERGE3';ftypes[3]='text';fnames[4]='MMERGE4';ftypes[4]='text';var err_style = '';
try{
    err_style = mc_custom_error_style;
} catch(e){
    err_style = 'margin: 1em 0 0 0; padding: 1em 0.5em 0.5em 0.5em; background: ERROR_BGCOLOR none repeat scroll 0% 0%; font-weight: bold; float: left; z-index: 1; width: 80%; -moz-background-clip: -moz-initial; -moz-background-origin: -moz-initial; -moz-background-inline-policy: -moz-initial; color: ERROR_COLOR;';
}
var mce_jQuery = jQuery.noConflict();
mce_jQuery(document).ready( function($) {
  var options = { errorClass: 'mce_inline_error', errorElement: 'div', errorStyle: err_style, onkeyup: function(){}, onfocusout:function(){}, onblur:function(){}  };
  var mce_validator = mce_jQuery("#mc-embedded-subscribe-form").validate(options);
  options = { url: 'http://joindiaspora.us1.list-manage2.com/subscribe/post-json?u=d759919b94f9cdcf39d204f3f&id=7b5ceb2f8b&c=?', type: 'GET', dataType: 'json', contentType: "application/json; charset=utf-8",
                beforeSubmit: function(){
                    mce_jQuery('#mce_tmp_error_msg').remove();
                    mce_jQuery('.datefield','#mc_embed_signup').each(
                        function(){
                            var txt = 'filled';
                            var fields = new Array();
                            var i = 0;
                            mce_jQuery(':text', this).each(
                                function(){
                                    fields[i] = this;
                                    i++;
                                });
                            mce_jQuery(':hidden', this).each(
                                function(){
                                	if ( fields[0].value=='MM' && fields[1].value=='DD' && fields[2].value=='YYYY' ){
                                		this.value = '';
									} else if ( fields[0].value=='' && fields[1].value=='' && fields[2].value=='' ){
                                		this.value = '';
									} else {
	                                    this.value = fields[0].value+'/'+fields[1].value+'/'+fields[2].value;
	                                }
                                });
                        });
                    return mce_validator.form();
                }, 
                success: mce_success_cb
            };
  mce_jQuery('#mc-embedded-subscribe-form').ajaxForm(options);

});
function mce_success_cb(resp){
    mce_jQuery('#mce-success-response').hide();
    mce_jQuery('#mce-error-response').hide();
    if (resp.result=="success"){
        mce_jQuery('#mce-'+resp.result+'-response').show();
        mce_jQuery('#mce-'+resp.result+'-response').html(resp.msg);
        mce_jQuery('#mc-embedded-subscribe-form').each(function(){
            this.reset();
    	});
    } else {
        var index = -1;
        var msg;
        try {
            var parts = resp.msg.split(' - ',2);
            if (parts[1]==undefined){
                msg = resp.msg;
            } else {
                i = parseInt(parts[0]);
                if (i.toString() == parts[0]){
                    index = parts[0];
                    msg = parts[1];
                } else {
                    index = -1;
                    msg = resp.msg;
                }
            }
        } catch(e){
            index = -1;
            msg = resp.msg;
        }
        try{
            if (index== -1){
                mce_jQuery('#mce-'+resp.result+'-response').show();
                mce_jQuery('#mce-'+resp.result+'-response').html(msg);            
            } else {
                err_id = 'mce_tmp_error_msg';
                html = '<div id="'+err_id+'" style="'+err_style+'"> '+msg+'</div>';
                
                var input_id = '#mc_embed_signup';
                var f = mce_jQuery(input_id);
                if (ftypes[index]=='address'){
                    input_id = '#mce-'+fnames[index]+'-addr1';
                    f = mce_jQuery(input_id).parent().parent().get(0);
                } else if (ftypes[index]=='date'){
                    input_id = '#mce-'+fnames[index]+'-month';
                    f = mce_jQuery(input_id).parent().parent().get(0);
                } else {
                    input_id = '#mce-'+fnames[index];
                    f = mce_jQuery().parent(input_id).get(0);
                }
                if (f){
                    mce_jQuery(f).append(html);
                    mce_jQuery(input_id).focus();
                } else {
                    mce_jQuery('#mce-'+resp.result+'-response').show();
                    mce_jQuery('#mce-'+resp.result+'-response').html(msg);
                }
            }
        } catch(e){
            mce_jQuery('#mce-'+resp.result+'-response').show();
            mce_jQuery('#mce-'+resp.result+'-response').html(msg);
        }
    }
}
</script>
<!--End mc_embed_signup-->

app/views/shared/_notification.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

= link_to t('.new', :type => object.class.to_s, :from => object.person.name), object_path(object.post)

app/views/shared/_public_explain.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.span-12.last
  .modal_title_bar
    %h4=t('.title')
  %p
    =t('.outside')
    %br
    %br

    - if current_user.services
      - for service in current_user.services 
        = t('.logged_in', :service => service.provider)
        %br

    = link_to t('.manage'), services_path

    %br
    %br
    = link_to t('ok'), '#', :class => "button", :onClick => '$.fancybox.close();'

app/views/shared/_publisher.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


- content_for :head do
  :javascript
    $(document).ready(function(){
      $("div.public_toggle input").live("click", function(evt){
        if($(this).attr('checked') == true){
          $(".question_mark").click(); 
        }; 
      });
      
      $("#publisher textarea, #publisher input").live("focus", function(evt){
        $("#publisher .options_and_submit").fadeIn(50);
      });

      $("#publisher form").live("submit", function(evt){
        $("#photodropzone").find('li').remove(); 
        $("#publisher .options_and_submit").hide();
      });

      $("#content_creation_button").bind("click", function(evt){
        $("#publisher").removeClass("closed");
        $("#publisher").find("textarea").focus();
      });
    });

#publisher{:class=>("closed" if aspect == :all)}

  - if aspect == :all
    #content_creation_button
      = image_tag 'icons/monotone_chat_talk.png', :id => 'share_bubble'
      %h4= t('.share_with_all')

  .content_creation
    = form_for(StatusMessage.new, :remote => true) do |status|
      %ul#photodropzone
      = status.error_messages
      #file-upload.button
        = t('.add_photos')

      %p
        %params
          - unless aspect == :all
            = status.label :message, t('.post_a_message_to', :aspect => (aspect == :all ? t('.all_contacts') : aspect))
          = status.text_area :message, :rows => 2, :value => params[:prefill]

      = status.hidden_field :aspect_ids, :value => (aspect == :all ? aspect : aspect.id)

      .options_and_submit

        .right
          #fileInfo
          = image_tag 'ajax-loader.gif', :class => 'hidden', :id => "publisher_spinner"
          - if aspect == :all
            = status.submit t('.share'), :title => t('.share_with_all'), :disable_with => t('.posting')
          - else
            = status.submit t('.share'), :title => t('.share_with', :aspect => aspect), :disable_with => t('.posting')

        - if aspect == :all
          .public_toggle
            %p.checkbox_select
              = status.check_box( :public, {}, true, false )
              = status.label :public, t('.make_public')
              = link_to (image_tag "social_media_logos/feed-16x16.png", :title => "RSS"), current_user.public_url 
              - if current_user.services
                - for service in current_user.services      
                  = image_tag "social_media_logos/#{service.provider}-16x16.png", :title => service.provider

            = link_to '(?)', "#question_mark_pane", :class => 'question_mark', :style=>"display:none;"

            .fancybox_content
              #question_mark_pane
                = render 'shared/public_explain'

    #publisher_photo_upload
      = render 'photos/new_photo', :aspect_id => (aspect == :all ? aspect : aspect.id)

app/views/shared/_publisher.mobile.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


#publisher
  = form_for StatusMessage.new, :remote => true do |status|
    %p
      = status.label :message, t('.post_a_message_to', :aspect => (aspect == :all ? t('.all') : aspect))
      = status.text_area :message, :rows => 2, :value => params[:prefill]

    = status.hidden_field :to, :value => (aspect == :all ? aspect : aspect.id)

    %fieldset{:class => 'ui-grid-a'}
      .options_and_submit
        %div{:class => 'ui-block-a'}
          - if aspect == :all
            = status.submit t('.share'), :title => t('.share_with_all')
          - else
            = status.submit t('.share'), :title => t('.share_with', :aspect => aspect)

        - if aspect == :all
          %div{:class => 'ui-block-a'}

            .public_toggle
              %p.checkbox_select
                = status.check_box( :public, {}, true, false )
                = status.label :public, t('.make_public')
              = link_to '(?)', "#question_mark_pane", :class => 'question_mark', :style=>"display:none;"

app/views/shared/_reshare.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.reshare_pane
  %span.reshare_button
    = link_to t('.reshare'), "#"

  %ul.reshare_box
    = aspect_links(aspects, :prefill => CGI::escape(post.message))

app/views/shared/_stream.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

%ul{:class => 'stream', :id => 'main_stream'}
  - for post_hash in posts
    = render 'shared/stream_element', post_hash.merge(:aspects => @aspects, :commenting_disabled => defined?(@commenting_disabled))

app/views/shared/_stream_element.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

%li.message{:data=>{:guid=>post.id}}
  - if person.owner_id == current_user.id
    .right.controls
      - reshare_aspects = aspects_without_post(aspects, post)
      - unless reshare_aspects.empty?
        = render 'shared/reshare', :aspects => reshare_aspects, :post => post
      = link_to t('delete'), status_message_path(post), :confirm => t('are_you_sure'), :method => :delete, :remote => true, :class => "delete"

  = person_image_link(person, :size => :thumb_small)

  .content
    .from
      %h4
        =person_link(person)

      - if post.public?
        %span.arrow ➔
        %span.aspect_badge.public
          = t('the_world')

      - elsif person.owner_id == current_user.id
        %span.arrow ➔
        = aspect_badge(aspects_with_post(aspects, post))


    = render 'status_messages/status_message', :post => post, :photos => photos

    .info
      %span.time= link_to(how_long_ago(post), status_message_path(post))
      = comment_toggle(comments.length, @commenting_disabled)

    = render "comments/comments", :post_id => post.id, :comment_hashes => comments, :condensed => true, :commenting_disabled => defined?(@commenting_disabled)

app/views/shared/_stream_element.mobile.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

%li.message{:data=>{:guid=>post.id}}
  = person_image_link(post.person)

  .content
    .from
      = link_to post.person.name, post.person
      .aspect
        ➔
        - if post.public?
          = t('the_world')
        - else
          = current_user.aspects_with_post( post.id ).join(', ')

    = render type_partial(post), :post => post

    .info
      %span.time= link_to(how_long_ago(post), object_path(post))
      /= link_to "#{t('.show_comments')} (#{post.comments.count})", '#', :class => "show_post_comments"

      - if current_user.owns?(post)
        .right
          = link_to t('delete'), photo_path(post), :confirm => t('are_you_sure'), :method => :delete, :remote => true, :class => "delete"
    /= render   "comments/comments", :post => post