config/routes.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

Diaspora::Application.routes.draw do
  resources :status_messages, :only => [:create, :destroy, :show]
  resources :comments,        :only => [:create]
  resources :requests,        :only => [:destroy, :create]
  resources :services
  resources :posts,           :only => [:show], :path => '/p/'



  match '/people/share_with' => 'people#share_with', :as => 'share_with'
  resources :people do
    resources :status_messages
    resources :photos
  end

  match '/people/by_handle' => 'people#retrieve_remote', :as => 'person_by_handle'
  match '/auth/:provider/callback' => 'services#create'
  match '/auth/failure' => 'services#failure'

  match 'photos/make_profile_photo' => 'photos#make_profile_photo'
  resources :photos, :except => [:index]

  devise_for :users, :controllers => {:registrations => "registrations",
                                      :password      => "devise/passwords",
                                      :invitations   => "invitations"}
  # added public route to user
  match 'public/:username',          :to => 'users#public'
  match 'getting_started',           :to => 'users#getting_started', :as => 'getting_started'
  match 'getting_started_completed', :to => 'users#getting_started_completed'
  match 'users/export',              :to => 'users#export'
  match 'users/export_photos',       :to => 'users#export_photos'
  match 'login',                     :to => 'users#sign_up'
  resources :users,                  :except => [:create, :new, :show]

  match 'aspects/move_contact',      :to => 'aspects#move_contact', :as => 'move_contact'
  match 'aspects/add_to_aspect',     :to => 'aspects#add_to_aspect', :as => 'add_to_aspect'
  match 'aspects/remove_from_aspect',:to => 'aspects#remove_from_aspect', :as => 'remove_from_aspect'
  match 'aspects/manage',            :to => 'aspects#manage'
  resources :aspects,                :except => [:edit]

  #public routes
  match 'webfinger',            :to => 'publics#webfinger'
  match 'hcard/users/:id',      :to => 'publics#hcard'
  match '.well-known/host-meta',:to => 'publics#host_meta'
  match 'receive/users/:id',    :to => 'publics#receive'
  match 'hub',                  :to => 'publics#hub'

  #root
  root :to => 'home#show'
end

app/models/aspect.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

class Aspect
  include MongoMapper::Document

  key :name,        String
  key :post_ids,    Array

  many :contacts, :foreign_key => 'aspect_ids', :class_name => 'Contact'
  many :posts,    :in => :post_ids, :class_name => 'Post'

  belongs_to :user, :class_name => 'User'

  validates_presence_of :name
  validates_length_of :name, :maximum => 20
  validates_uniqueness_of :name, :scope => :user_id
  attr_accessible :name
  
  before_validation do
    name.strip!
  end
  
  timestamps!

  def to_s
    name
  end
  
  def person_objects
    person_ids = people.map{|x| x.person_id}
    Person.all(:id.in => person_ids)
  end

  def as_json(opts = {})
    {
      :aspect => {
        :name   => self.name,
        :people => self.people.each{|person| person.as_json},
        :posts  => self.posts.each {|post|   post.as_json  },
      }
    }
  end

end

app/controllers/aspects_controller.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

class AspectsController < ApplicationController
  before_filter :authenticate_user!

  respond_to :html
  respond_to :json, :only => :show

  def index
    @posts  = current_user.visible_posts(:_type => "StatusMessage").paginate :page => params[:page], :per_page => 15, :order => 'created_at DESC'
    @post_hashes = hashes_for_posts @posts
    @contacts = Contact.all(:user_id => current_user.id, :pending => false)
    @aspect_hashes = hashes_for_aspects @aspects.all, @contacts, :limit => 8
    @aspect = :all

    @contact_hashes = hashes_for_contacts @contacts

    if current_user.getting_started == true
      redirect_to getting_started_path
    end
  end

  def create
    @aspect = current_user.aspects.create(params[:aspect])
    if @aspect.valid?
      flash[:notice] = I18n.t('aspects.create.success', :name => @aspect.name)
      if current_user.getting_started
        redirect_to :back
      elsif request.env['HTTP_REFERER'].include?("aspects/manage")
        redirect_to :back
      else
        respond_with @aspect
      end
    else
      flash[:error] = I18n.t('aspects.create.failure')
      redirect_to :back
    end
  end

  def new
    @aspect = Aspect.new
  end

  def destroy
    @aspect = current_user.aspect_by_id params[:id]

    begin
      current_user.drop_aspect @aspect
      flash[:notice] = I18n.t 'aspects.destroy.success',:name => @aspect.name
      redirect_to root_url
    rescue RuntimeError => e
      flash[:error] = e.message
      redirect_to :back
    end
  end

  def show
    @aspect = current_user.aspect_by_id params[:id]
    @contacts = current_user.contacts(:pending => false)
    unless @aspect
      render :file => "#{Rails.root}/public/404.html", :layout => false, :status => 404
    else
      @aspect_contacts = hashes_for_contacts Contact.all(:user_id => current_user.id, :aspect_ids.in => [@aspect.id], :pending => false)
      @aspect_contacts_count = @aspect_contacts.count

      @posts = @aspect.posts.find_all_by__type("StatusMessage", :order => 'created_at desc').paginate :page => params[:page], :per_page => 15
      @post_hashes = hashes_for_posts @posts
      @post_count = @posts.count

      respond_with @aspect
    end
  end

  def manage
    @aspect = :manage
    @contacts = current_user.contacts(:pending => false)
    @remote_requests = Request.hashes_for_person(current_user.person)
    @aspect_hashes = hashes_for_aspects @aspects, @contacts
  end

  def update
    @aspect = current_user.aspect_by_id(params[:id])
    if @aspect.update_attributes( params[:aspect] )
      flash[:notice] = I18n.t 'aspects.update.success',:name => @aspect.name
    else
      flash[:error] = I18n.t 'aspects.update.failure',:name => @aspect.name
    end
    respond_with @aspect
  end

  def move_contact
    @person = Person.find(params[:person_id])
    @from_aspect = current_user.aspects.find(params[:from])
    @to_aspect = current_user.aspects.find(params[:to][:to])

    unless current_user.move_contact( @person, @from_aspect, @to_aspect)
      flash[:error] = I18n.t 'aspects.move_contact.error',:inspect => params.inspect
    end
    if aspect = current_user.aspect_by_id(params[:to][:to])
      flash[:notice] = I18n.t 'aspects.move_contact.success'
      render :nothing => true
    else
      flash[:notice] = I18n.t 'aspects.move_contact.failure'
      render aspects_manage_path
    end
  end

  def add_to_aspect
    @person = Person.find(params[:person_id])
    @aspect = current_user.aspects.find(params[:aspect_id])
    @contact = current_user.contact_for(@person)

    if @contact
      current_user.add_contact_to_aspect(@contact, @aspect)
    else
      current_user.send_contact_request_to(@person, @aspect)
      contact = current_user.contact_for(@person)

      if request = Request.from(@person).to(current_user).first
        request.destroy
        contact.update_attributes(:pending => false)
      end
    end
    flash.now[:notice] =  I18n.t 'aspects.add_to_aspect.success'

    respond_to do |format|
      format.js { render :json => {
        :button_html => render_to_string(:partial => 'aspects/add_to_aspect',
                         :locals => {:aspect_id => @aspect.id,
                                     :person_id => @person.id}),
        :badge_html =>  render_to_string(:partial => 'aspects/aspect_badge',
                            :locals => {:aspect => @aspect})
        }}
      format.html{ redirect_to aspect_path(@aspect.id)}
    end
  end

  def remove_from_aspect
    begin current_user.delete_person_from_aspect(params[:person_id], params[:aspect_id])
      @person_id = params[:person_id]
      @aspect_id = params[:aspect_id]
      flash.now[:notice] = I18n.t 'aspects.remove_from_aspect.success'

      respond_to do |format|
        format.js { render :json => {:button_html =>
          render_to_string(:partial => 'aspects/remove_from_aspect',
                           :locals => {:aspect_id => @aspect_id,
                                       :person_id => @person_id}),
          :aspect_id => @aspect_id
        }}
        format.html{
          redirect_to :back
        }
      end
    rescue Exception => e
      flash.now[:error] = I18n.t 'aspects.remove_from_aspect.failure'

      respond_to do |format|
        format.js  { render :text => e, :status => 403 }
        format.html{
          redirect_to :back
        }
      end
    end
  end

  private
  def hashes_for_contacts contacts
    people = Person.all(:id.in => contacts.map{|c| c.person_id}, :fields => [:profile])
    people_hash = {}
    people.each{|p| people_hash[p.id] = p}
    contacts.map{|c| {:contact => c, :person => people_hash[c.person_id.to_id]}}
  end

  def hashes_for_aspects aspects, contacts, opts = {}
    contact_hashes = hashes_for_contacts contacts
    aspects.map do |a|
      hash = {:aspect => a}
      aspect_contact_hashes = contact_hashes.select{|c|
          c[:contact].aspect_ids.include?(a.id)}
      hash[:contact_count] = aspect_contact_hashes.count
      if opts[:limit]
        hash[:contacts] = aspect_contact_hashes.slice(0,opts[:limit])
      else
        hash[:contacts] = aspect_contact_hashes
      end
      hash
    end
  end
  def hashes_for_posts posts
    post_ids = posts.map{|p| p.id}
    comment_hash = Comment.hash_from_post_ids post_ids
    person_hash = Person.from_post_comment_hash comment_hash
    photo_hash = Photo.hash_from_post_ids post_ids

    posts.map do |post|
      {:post => post,
        :photos => photo_hash[post.id],
        :person => post.person,
        :comments => comment_hash[post.id].map do |comment|
          {:comment => comment,
            :person => person_hash[comment.person_id],
          }
        end,
      }
    end
  end
end

app/helpers/aspects_helper.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

module AspectsHelper
  def link_for_aspect( aspect )
    link_to aspect.name, aspect
  end

  def remove_link( aspect )
    if aspect.contacts.size == 0
      link_to I18n.t('aspects.helper.remove'), aspect, :method => :delete, :confirm => I18n.t('aspects.helper.are_you_sure')
    else
      "<span class='grey' title=#{I18n.t('aspects.helper.aspect_not_empty')}>#{I18n.t('aspects.helper.remove')}</span>"
    end
  end

  def add_to_aspect_button(aspect_id, person_id)
    link_to image_tag('icons/monotone_plus_add_round.png'),
      {:controller => "aspects",
        :action => 'add_to_aspect',
        :aspect_id => aspect_id,
        :person_id => person_id},
      :remote => true,
      :class => 'add button'
  end

  def remove_from_aspect_button(aspect_id, person_id)
    link_to image_tag('icons/monotone_check_yes.png'),
      {:controller => "aspects",
        :action => 'remove_from_aspect',
        :aspect_id => aspect_id,
        :person_id => person_id},
      :remote => true,
      :class => 'added button'
  end

  def aspect_membership_button(aspect_id, contact, person)
    if contact.nil? || !contact.aspect_ids.include?(aspect_id)
      add_to_aspect_button(aspect_id, person.id)
    else
      remove_from_aspect_button(aspect_id, person.id)
    end
  end
end

app/views/aspects/_add_to_aspect.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


= remove_from_aspect_button(aspect_id,person_id)

app/views/aspects/_all_aspects_contacts.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- if @request_count > 0
  #new_request_pane{:class => "everyone"}
    %h1.new_request{:style => 'text-align:center'}
      = new_request_link(@request_count)

#left_pane.everyone

  .section.aspect_listings
    %h3
      = link_to(t('.aspects'), aspects_manage_path)
      .right{:style=>"font-size:12px;top:7px;"}
        = link_to t('.add_aspect'), '#add_aspect_pane', :class => "add_aspect_button"

    %ul
      - for a_hash in @aspect_hashes
        = render :partial => 'aspects/aspect', :locals => a_hash

  .section.contact_pictures
    %h3
      = t('.all_contacts')

    - for contact in @contact_hashes
      = person_image_link(contact[:person])

    - if @contacts.count == 0
      %h4
        = t('.no_contacts')
      = form_tag(people_path, :method => 'get') do
        = text_field_tag 'q', nil, :placeholder => t('search'), :type => 'search', :results => 5

  .section
    %h3= t('shared.invitations.invites')
    = render "shared/invitations", :invites => @invites

app/views/aspects/_aspect_contacts.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- content_for :head do
  =javascript_include_tag 'aspect-contacts'
  :javascript
    EditPane.setTranslations({
      doneEditing: "#{t('.done_editing')}",
      editAspect:"#{t('aspects.show.edit_aspect')}"
    });

  - if aspect.contacts.count == 0
    :javascript
      $(document).ready(function(){
        EditPane.fadeIn();
      });

#left_pane
  .section.contact_pictures
    - for contact in contacts
      = person_image_link(contact[:person])

    %br
    %br
    %br
    .section
      %h3= t('shared.invitations.invites')
      = render "shared/invitations", :invites => @invites

app/views/aspects/_edit_aspect_pane.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- content_for :head do
  = include_javascripts :aspects

#edit_aspect_pane
  - if @contacts.count > 0
    %h4= t('.add_existing')
    = render 'shared/contact_list', :aspect_id => aspect.id, :contact_hashes => contacts, :manage => defined?(manage)

  = render 'shared/add_contact', :aspect_id => aspect.id

  %hr
  = form_for aspect do |asp|
    = asp.text_field :name, :value => aspect.name
    = asp.submit "Rename Aspect"

  %hr
  .big_buttons
    = button_to t('.remove_aspect'), aspect, :method => "delete", :confirm => t('.confirm_remove_aspect')

app/views/aspects/_new_aspect.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.span-12.last
  .modal_title_bar
    %h4= t('aspects.manage.add_a_new_aspect')

  = form_for Aspect.new do |aspect|
    = aspect.error_messages
    %p
      = aspect.label :name , t('.name')
      = aspect.text_field :name, :maxlength => 20
    = aspect.submit t('.create'), :class => 'button'

app/views/aspects/_no_contacts_message.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

#no_contacts.floating.empty_message{:style => ("display:none" unless contact_count == 0)}
  - if aspect == :all
    %h3=t('.nobody')
    %h4= link_to t('.invite'), new_user_invitation_path
  - else
    %h3=t('.nobody_in_aspect', :aspect_name => aspect.name)

app/views/aspects/_remove_from_aspect.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


= add_to_aspect_button(aspect_id,person_id)

app/views/aspects/add_to_aspect.js.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


= remove_from_aspect_button(@aspect_id,@person_id)

app/views/aspects/index.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.span-24.last
  %h2{:style => "position:relative;"}
    = current_user.name
    .right{:style=>"top:0"}
      %span.description
        = link_to current_user.diaspora_handle, person_path(current_user.person)
        = info_text(t('.handle_explanation'))

.span-15.append-1
  = render 'shared/publisher', :aspect => @aspect
  = render 'aspects/no_contacts_message', :aspect => @aspect, :contact_count => @contacts.count
  = render 'aspects/no_posts_message', :post_count => @post_hashes.length, :contact_count => @contacts.count

  = render 'shared/stream', :posts => @post_hashes

  #pagination
    = will_paginate @posts

.span-8.last
  = render 'aspects/all_aspects_contacts'

app/views/aspects/index.mobile.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

%div
  %h1
    = person_image_tag (current_user.person)
    = current_user.name
= select_tag "aspect_picker", aspect_select_options(@aspects, @aspect)

%div{:data => {:role => 'content'}}
  %div{:data => {:role => 'fieldcontain'}}
    =render 'shared/publisher', :aspect => @aspect

= render 'shared/stream', :posts => @posts

app/views/aspects/manage.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- content_for :head do
  = include_javascripts :aspects

- content_for :page_title do
  = t('.manage_aspects')

#section_header
  %h2=t('.manage_aspects')
  .right{:style=>"top:0;"}
    = link_to("+ #{t('.add_a_new_aspect')}", "#add_aspect_pane", :class => "new_aspect add_aspect_button button", :title => t('.add_a_new_aspect'))

#manage_aspect_zones
  .span-4.append-1.last
    .requests
      %h3=t('.requests')
      %i
        %p= "#{t('.drag_to_add')} =>"

      %ul.dropzone
        - if @remote_requests.size < 1
          %li=t('.no_requests')
        - else
          - for hash in @remote_requests
            %li.person.request{:data=>{:guid=>hash[:request].id, :person_id=>hash[:sender].id}}
              .delete
                .x
                  X
                .circle
              = link_to person_image_tag(hash[:sender]), hash[:sender]

      = render 'shared/invitations', :invites => @invites

    %div{:style=>"color:rgb(252,252,252);"}
      \.

  .span-19.last
    - for hash in @aspect_hashes
      .aspect.span-9{:data=>{:guid=>hash[:aspect].id}}
        .aspect_name
          %span.edit_name_field
            %h3{:contenteditable=>true}
              = hash[:aspect].name
            %span.tip click to edit

          %ul.tools
            %li= link_to t('.add_a_new_contact'), "#manage_aspect_contacts_pane_#{hash[:aspect].id}", :class => 'manage_aspect_contacts_button'
            %li!= remove_link(hash[:aspect])

        %ul.dropzone{:data=>{:aspect_id=>hash[:aspect].id}}
          -for contact_hash in hash[:contacts]
            %li.person{:data=>{:guid=>contact_hash[:person].id, :aspect_id=>hash[:aspect].id}}
              .delete
                .x
                  X
                .circle
              = link_to person_image_tag(contact_hash[:person]), contact_hash[:person]
          .draggable_info
            =t('.drag_to_add')

          .fancybox_content
            %div{:id => "manage_aspect_contacts_pane_#{hash[:aspect].id}"}
              = render "requests/manage_aspect_contacts", :aspect => hash[:aspect], :manage => true, :contact_hashes => hash[:contacts]

app/views/aspects/remove_from_aspect.js.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


= add_to_aspect_button(@aspect_id,@person_id)

app/views/aspects/show.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- content_for :page_title do
  = @aspect.name

.span-24.last
  %h2{:style=>"position:relative;margin-bottom:0;"}
    = @aspect

  %span.aspect_contact_count{:style=>"color:#999;font-size:14px;"}
    = t('contacts', :count=>@aspect_contacts_count)
    = link_to t('.edit_aspect'), "#", :id => "edit_aspect_trigger"

.span-8.append-1
  = render 'aspects/aspect_contacts', :contacts => @aspect_contacts, :aspect => @aspect
  = render 'aspects/edit_aspect_pane', :contacts => @aspect_contacts, :aspect => @aspect


.span-15.last
  = render 'shared/publisher', :aspect => @aspect
  = render 'aspects/no_contacts_message', :aspect => @aspect, :contact_count => @aspect_contacts_count, :options => false
  = render 'aspects/no_posts_message', :post_count => @post_count, :contact_count=> @aspect_contacts_count

  = render 'shared/stream', :posts => @post_hashes

  #pagination
    = will_paginate @posts

app/views/aspects/show.mobile.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

= render 'shared/publisher', :aspect => @aspect

= render 'shared/stream', :posts => @posts

#pagination 
  = will_paginate @posts